network_params:
  # input size
  seq_len: 512
  batch_size: 64
  # feature size
  head_num: 16
  head_dim: 64
  token_dim: 1024
  ffn_hidden_dim: 4096
  layer_num: 24

system_params:
  # for dpu
  dpu_num: 1024
  nr_tasklets: 16
  qkv_lut_pim_binary: "./build/bin/dpu_bin_qkv"
  o_lut_pim_binary: "./build/bin/dpu_bin_o"
  ffn1_lut_pim_binary: "./build/bin/dpu_bin_ffn1"
  ffn2_lut_pim_binary: "./build/bin/dpu_bin_ffn2"
  # for cpu
  num_threads: 40

kernel_params:
  # for qkv lut
  qkv_num_codebook: 512
  qkv_num_centroid: 16

  # for o lut
  o_num_codebook: 512
  o_num_centroid: 16

  # for ffn1 lut
  ffn1_num_codebook: 512
  ffn1_num_centroid: 16

  # for ffn2 lut
  ffn2_num_codebook: 2048
  ffn2_num_centroid: 16
